// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { supabase } from "./client";

// Cache session token to avoid calling getSession() on every server function invocation
// Token is cached for 1 minute, then refreshed
let cachedToken: { token: string | null; expires: number } | null = null;

// Invalidate cache on any auth state change (logout, token refresh, session expiry)
supabase.auth.onAuthStateChange((_event, session) => {
  cachedToken = null; // Force re-fetch on next server function call
});

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    const now = Date.now();
    
    // Check if we have a valid cached token
    if (!cachedToken || cachedToken.expires < now) {
      const { data } = await supabase.auth.getSession();
      cachedToken = {
        token: data.session?.access_token ?? null,
        expires: now + 60_000, // Cache for 1 minute
      };
    }
    
    return next({
      headers: cachedToken.token ? { Authorization: `Bearer ${cachedToken.token}` } : {},
    });
  },
);
