/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LibraryListIdRouteImport } from './routes/library.$listId'
import { Route as MovieImdbIdRouteImport } from './routes/movie.$imdbId'
import { Route as ApiPublicSyncPushRouteImport } from './routes/api/public/sync/push'
import { Route as ApiTmdbImageSplatRouteImport } from './routes/api/tmdb/image.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryListIdRoute = LibraryListIdRouteImport.update({
  id: '/$listId',
  path: '/$listId',
  getParentRoute: () => LibraryRoute,
} as any)
const MovieImdbIdRoute = MovieImdbIdRouteImport.update({
  id: '/movie/$imdbId',
  path: '/movie/$imdbId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncPushRoute = ApiPublicSyncPushRouteImport.update({
  id: '/api/public/sync/push',
  path: '/api/public/sync/push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTmdbImageSplatRoute = ApiTmdbImageSplatRouteImport.update({
  id: '/api/tmdb/image/$',
  path: '/api/tmdb/image/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/credits': typeof CreditsRoute
  '/library': typeof LibraryRouteWithChildren
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/library/$listId': typeof LibraryListIdRoute
  '/movie/$imdbId': typeof MovieImdbIdRoute
  '/api/public/sync/push': typeof ApiPublicSyncPushRoute
  '/api/tmdb/image/$': typeof ApiTmdbImageSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/credits': typeof CreditsRoute
  '/library': typeof LibraryRouteWithChildren
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/library/$listId': typeof LibraryListIdRoute
  '/movie/$imdbId': typeof MovieImdbIdRoute
  '/api/public/sync/push': typeof ApiPublicSyncPushRoute
  '/api/tmdb/image/$': typeof ApiTmdbImageSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/credits': typeof CreditsRoute
  '/library': typeof LibraryRouteWithChildren
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/library/$listId': typeof LibraryListIdRoute
  '/movie/$imdbId': typeof MovieImdbIdRoute
  '/api/public/sync/push': typeof ApiPublicSyncPushRoute
  '/api/tmdb/image/$': typeof ApiTmdbImageSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/credits'
    | '/library'
    | '/login'
    | '/search'
    | '/settings'
    | '/setup'
    | '/library/$listId'
    | '/movie/$imdbId'
    | '/api/public/sync/push'
    | '/api/tmdb/image/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/credits'
    | '/library'
    | '/login'
    | '/search'
    | '/settings'
    | '/setup'
    | '/library/$listId'
    | '/movie/$imdbId'
    | '/api/public/sync/push'
    | '/api/tmdb/image/$'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/credits'
    | '/library'
    | '/login'
    | '/search'
    | '/settings'
    | '/setup'
    | '/library/$listId'
    | '/movie/$imdbId'
    | '/api/public/sync/push'
    | '/api/tmdb/image/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CreditsRoute: typeof CreditsRoute
  LibraryRoute: typeof LibraryRouteWithChildren
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  MovieImdbIdRoute: typeof MovieImdbIdRoute
  ApiPublicSyncPushRoute: typeof ApiPublicSyncPushRoute
  ApiTmdbImageSplatRoute: typeof ApiTmdbImageSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$listId': {
      id: '/library/$listId'
      path: '/$listId'
      fullPath: '/library/$listId'
      preLoaderRoute: typeof LibraryListIdRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/movie/$imdbId': {
      id: '/movie/$imdbId'
      path: '/movie/$imdbId'
      fullPath: '/movie/$imdbId'
      preLoaderRoute: typeof MovieImdbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync/push': {
      id: '/api/public/sync/push'
      path: '/api/public/sync/push'
      fullPath: '/api/public/sync/push'
      preLoaderRoute: typeof ApiPublicSyncPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tmdb/image/$': {
      id: '/api/tmdb/image/$'
      path: '/api/tmdb/image/$'
      fullPath: '/api/tmdb/image/$'
      preLoaderRoute: typeof ApiTmdbImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LibraryRouteChildren {
  LibraryListIdRoute: typeof LibraryListIdRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryListIdRoute: LibraryListIdRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CreditsRoute: CreditsRoute,
  LibraryRoute: LibraryRouteWithChildren,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  MovieImdbIdRoute: MovieImdbIdRoute,
  ApiPublicSyncPushRoute: ApiPublicSyncPushRoute,
  ApiTmdbImageSplatRoute: ApiTmdbImageSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
